version: '3'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - ALLOW_IP_RANGE=0.0.0.0/0

  web:
    build: .
    image: kube_web:0.0.1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todo
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD

