apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - image: todaatsushi0/todo:0.0.1
          name: todo
          envFrom:
            - secretRef:
                name: todo-secret
            - configMapRef:
                name: todo-config
          ports:
            - containerPort: 8000
              name: local
